### ISSUE TITLE
Refactor login screen design

### ISSUE THREAD

**Issue by sterapps** [snypy/snypy-frontend#1029]

**Comment by nezhar** [comment]
Current state:
![Selection_064](https://user-images.githubusercontent.com/4420927/159118108-5408b2d8-c154-4979-a377-7dd77debf845.png)

**Comment by nezhar** [comment]
@sterapps not sure, but can we use https://www.anglify.io/components/form-field for this?

**Comment by nezhar** [comment]
Thanks @sterapps for designing and implementing the new login screen
![Selection_073](https://user-images.githubusercontent.com/4420927/165840897-623eb21e-92f3-4223-9fc0-649929904029.png)
