### ISSUE TITLE
Refactor: Delete Snippet Modal

### ISSUE THREAD

**Issue by sterapps** [snypy/snypy-frontend#1607]
<img width="500" alt="Screenshot 2022-10-21 at 17 19 09" src="https://user-images.githubusercontent.com/60810159/197230825-164c1f07-7edf-4178-b8a9-43f2a3fb8eae.png">

**Comment by nezhar** [comment]
The new modal looks great :tada: 
![image](https://user-images.githubusercontent.com/4420927/197414463-1a03b0a3-cc18-4d87-9a2f-9a5c0ebb137b.png)
