### ISSUE TITLE
Demo instance username and password

### ISSUE THREAD

**Issue by SuperDarius-git** [snypy/snypy-frontend#2317]
I have searched everywhere, but could not find the username and password for the demo instance. I just want to have a look to see if it has the features I need. I tried to register,but it doesn't work. Please could someone help me with this?

**Comment by nezhar** [comment]
Hi @SuperDarius-git, you should check you mail for an aktivation link, maybe it got into spam. Otherwise you may try to setup a local environment using https://github.com/snypy/snypy-docker
