### ISSUE TITLE
DataAccess Module for OpenAPI Specification

### ISSUE THREAD

**Issue by sterapps** [snypy/snypy-frontend#791]
Specification URL: https://api.snypy.com/api/v1/schema/swagger-ui/

**Comment by nezhar** [comment]
Docs:
* https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-angular.md
* https://openapi-generator.tech/docs/generators/typescript-angular/

**Comment by nezhar** [comment]
Cleint is currently generated manually:
```
docker run -u $(id -u ${USER}):$(id -g ${USER}) --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i https://github.com/snypy/snypy-backend/releases/download/1.0.0/openapi.yaml \
    -g typescript-angular \
    -o /local/client \
    --additional-properties=npmName=@snypy/rest-client,supportsES6=true,withInterfaces=true,npmVersion=1.0.0
```

An published to https://www.npmjs.com/package/@snypy/rest-client

It requires some manual steps for now:

- OpenAPI yaml needs to be downloaded and uploaded to a release on https://github.com/snypy/snypy-backend (will be covered by https://github.com/snypy/snypy-backend/issues/77)
- To above command needs to be executed locally and the generated package has to be uploaded to `npm` (will be automated with https://github.com/snypy/snypy-docker/issues/13)

**Comment by nezhar** [comment]
It seems that the installation of the module still has some issue.

**Comment by nezhar** [comment]
Fixed by splitting request and response components in openapi.

Also the created package needs to be build before published to npm.

```
docker run -u $(id -u ${USER}):$(id -g ${USER}) --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i https://github.com/snypy/snypy-backend/releases/download/1.0.1/openapi.yaml \
    -g typescript-angular \
    -o /local/client \
    --additional-properties=npmName=@snypy/rest-client,npmVersion=1.0.1

cd client
npm install --force
npm run build

cd dist
npm publish --access public
```
